//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_gates_H
#define METASPRITE_gates_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gates_TILE_ORIGIN 40
#define gates_TILE_W 8
#define gates_TILE_H 8
#define gates_WIDTH 160
#define gates_HEIGHT 128
#define gates_TILE_COUNT 0
#define gates_PALETTE_COUNT 1
#define gates_COLORS_PER_PALETTE 4
#define gates_TOTAL_COLORS 4
#define gates_MAP_ATTRIBUTES 0
extern const unsigned char gates_map[320];
#define gates_map_attributes gates_map

BANKREF_EXTERN(gates)


#endif
