//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_level_4_1_H
#define METASPRITE_level_4_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_4_1_TILE_ORIGIN 40
#define level_4_1_TILE_W 8
#define level_4_1_TILE_H 8
#define level_4_1_WIDTH 3520
#define level_4_1_HEIGHT 128
#define level_4_1_TILE_COUNT 35
#define level_4_1_PALETTE_COUNT 1
#define level_4_1_COLORS_PER_PALETTE 4
#define level_4_1_TOTAL_COLORS 4
#define level_4_1_MAP_ATTRIBUTES 0
extern const unsigned char level_4_1_map[7040];
#define level_4_1_map_attributes level_4_1_map

BANKREF_EXTERN(level_4_1)

extern const uint8_t level_4_1_tiles[560];

#endif
