//AUTOGENERATED FILE FROM png2asset
// Conversion args: /2_1_00.png -o /level_2_1_00.c -source_tileset /common.png -source_tileset /muda.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_level_2_1_00_H
#define METASPRITE_level_2_1_00_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_2_1_00_TILE_ORIGIN 40
#define level_2_1_00_TILE_W 8
#define level_2_1_00_TILE_H 8
#define level_2_1_00_WIDTH 160
#define level_2_1_00_HEIGHT 128
#define level_2_1_00_TILE_COUNT 0
#define level_2_1_00_PALETTE_COUNT 1
#define level_2_1_00_COLORS_PER_PALETTE 4
#define level_2_1_00_TOTAL_COLORS 4
#define level_2_1_00_MAP_ATTRIBUTES 0
extern const unsigned char level_2_1_00_map[320];
#define level_2_1_00_map_attributes level_2_1_00_map

BANKREF_EXTERN(level_2_1_00)


#endif
