//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_level_room_H
#define METASPRITE_level_room_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_room_TILE_ORIGIN 40
#define level_room_TILE_W 8
#define level_room_TILE_H 8
#define level_room_WIDTH 160
#define level_room_HEIGHT 128
#define level_room_TILE_COUNT 0
#define level_room_PALETTE_COUNT 1
#define level_room_COLORS_PER_PALETTE 4
#define level_room_TOTAL_COLORS 4
#define level_room_MAP_ATTRIBUTES 0
extern const unsigned char level_room_map[320];
#define level_room_map_attributes level_room_map

BANKREF_EXTERN(level_room)


#endif
