//AUTOGENERATED FILE FROM png2asset
// Conversion args: /4_3_12.png -o /level_4_3_12.c -source_tileset /common.png -source_tileset /chai.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_level_4_3_12_H
#define METASPRITE_level_4_3_12_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_4_3_12_TILE_ORIGIN 40
#define level_4_3_12_TILE_W 8
#define level_4_3_12_TILE_H 8
#define level_4_3_12_WIDTH 160
#define level_4_3_12_HEIGHT 128
#define level_4_3_12_TILE_COUNT 0
#define level_4_3_12_PALETTE_COUNT 1
#define level_4_3_12_COLORS_PER_PALETTE 4
#define level_4_3_12_TOTAL_COLORS 4
#define level_4_3_12_MAP_ATTRIBUTES 0
extern const unsigned char level_4_3_12_map[320];
#define level_4_3_12_map_attributes level_4_3_12_map

BANKREF_EXTERN(level_4_3_12)


#endif
