//AUTOGENERATED FILE FROM png2asset
// Conversion args: /4_3_11.png -o /level_4_3_11.c -source_tileset /common.png -source_tileset /chai.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_level_4_3_11_H
#define METASPRITE_level_4_3_11_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_4_3_11_TILE_ORIGIN 40
#define level_4_3_11_TILE_W 8
#define level_4_3_11_TILE_H 8
#define level_4_3_11_WIDTH 160
#define level_4_3_11_HEIGHT 128
#define level_4_3_11_TILE_COUNT 0
#define level_4_3_11_PALETTE_COUNT 1
#define level_4_3_11_COLORS_PER_PALETTE 4
#define level_4_3_11_TOTAL_COLORS 4
#define level_4_3_11_MAP_ATTRIBUTES 0
extern const unsigned char level_4_3_11_map[320];
#define level_4_3_11_map_attributes level_4_3_11_map

BANKREF_EXTERN(level_4_3_11)


#endif
