//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_level_1_1_0_H
#define METASPRITE_level_1_1_0_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_1_1_0_TILE_ORIGIN 40
#define level_1_1_0_TILE_W 8
#define level_1_1_0_TILE_H 8
#define level_1_1_0_WIDTH 1200
#define level_1_1_0_HEIGHT 128
#define level_1_1_0_TILE_COUNT 0
#define level_1_1_0_PALETTE_COUNT 1
#define level_1_1_0_COLORS_PER_PALETTE 4
#define level_1_1_0_TOTAL_COLORS 4
#define level_1_1_0_MAP_ATTRIBUTES 0
extern const unsigned char level_1_1_0_map[2400];
#define level_1_1_0_map_attributes level_1_1_0_map

BANKREF_EXTERN(level_1_1_0)


#endif
