//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_level_4_2_H
#define METASPRITE_level_4_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_4_2_TILE_ORIGIN 40
#define level_4_2_TILE_W 8
#define level_4_2_TILE_H 8
#define level_4_2_WIDTH 3040
#define level_4_2_HEIGHT 128
#define level_4_2_TILE_COUNT 23
#define level_4_2_PALETTE_COUNT 1
#define level_4_2_COLORS_PER_PALETTE 4
#define level_4_2_TOTAL_COLORS 4
#define level_4_2_MAP_ATTRIBUTES 0
extern const unsigned char level_4_2_map[6080];
#define level_4_2_map_attributes level_4_2_map

BANKREF_EXTERN(level_4_2)

extern const uint8_t level_4_2_tiles[368];

#endif
