//AUTOGENERATED FILE FROM png2asset
// Conversion args: /4_3_02.png -o /level_4_3_02.c -source_tileset /common.png -source_tileset /chai.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_level_4_3_02_H
#define METASPRITE_level_4_3_02_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_4_3_02_TILE_ORIGIN 40
#define level_4_3_02_TILE_W 8
#define level_4_3_02_TILE_H 8
#define level_4_3_02_WIDTH 160
#define level_4_3_02_HEIGHT 128
#define level_4_3_02_TILE_COUNT 0
#define level_4_3_02_PALETTE_COUNT 1
#define level_4_3_02_COLORS_PER_PALETTE 4
#define level_4_3_02_TOTAL_COLORS 4
#define level_4_3_02_MAP_ATTRIBUTES 0
extern const unsigned char level_4_3_02_map[320];
#define level_4_3_02_map_attributes level_4_3_02_map

BANKREF_EXTERN(level_4_3_02)


#endif
