//AUTOGENERATED FILE FROM png2asset
// Conversion args: /1_3_07.png -o /level_1_3_07.c -source_tileset /common.png -source_tileset /birabuto.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_level_1_3_07_H
#define METASPRITE_level_1_3_07_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_1_3_07_TILE_ORIGIN 40
#define level_1_3_07_TILE_W 8
#define level_1_3_07_TILE_H 8
#define level_1_3_07_WIDTH 160
#define level_1_3_07_HEIGHT 128
#define level_1_3_07_TILE_COUNT 0
#define level_1_3_07_PALETTE_COUNT 1
#define level_1_3_07_COLORS_PER_PALETTE 4
#define level_1_3_07_TOTAL_COLORS 4
#define level_1_3_07_MAP_ATTRIBUTES 0
extern const unsigned char level_1_3_07_map[320];
#define level_1_3_07_map_attributes level_1_3_07_map

BANKREF_EXTERN(level_1_3_07)


#endif
