//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_level_gates_H
#define METASPRITE_level_gates_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_gates_TILE_ORIGIN 40
#define level_gates_TILE_W 8
#define level_gates_TILE_H 8
#define level_gates_WIDTH 160
#define level_gates_HEIGHT 128
#define level_gates_TILE_COUNT 0
#define level_gates_PALETTE_COUNT 1
#define level_gates_COLORS_PER_PALETTE 4
#define level_gates_TOTAL_COLORS 4
#define level_gates_MAP_ATTRIBUTES 0
extern const unsigned char level_gates_map[320];
#define level_gates_map_attributes level_gates_map

BANKREF_EXTERN(level_gates)


#endif
