#pragma bank 255

#include "lookup_table_3_3.h"

BANKREF(level_3_3_lookup)

const level_object level_3_3_lookup[] = {
    {.x = 23,
     .y = 10,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 32,
     .y = 11,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 36,
     .y = 2,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 45,
     .y = 3,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 76,
     .y = 14,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {
        .x = 78,
        .y = 6,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 79,
        .y = 6,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {.x = 80,
     .y = 11,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 81,
     .y = 3,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 106,
     .y = 14,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KUMO}},
    {.x = 109,
     .y = 5,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 114,
     .y = 14,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KUMO}},
    {.x = 119,
     .y = 12,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 181,
     .y = 14,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 186,
     .y = 14,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 222,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BATADON}},
    {.x = 228,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_TOKOTOKO}},
    {.x = 273,
     .y = 5,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BATADON}},
    {.x = 293,
     .y = 12,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HIYOIHOI}}};
