#pragma bank 255

#include "lookup_table_2_1.h"

BANKREF(level_2_1_lookup_bank)

const level_object level_2_1_lookup[] = {
    {.x = 28,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 32,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 53,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 57,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 63,
     .y = 10,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.platform_direction = DIRECTION_HORIZONTAL}},
    {.x = 65,
     .y = 6,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.platform_direction = DIRECTION_HORIZONTAL}},
    {.x = 104,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 111,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 122,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 129,
     .y = 6,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 129,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 131,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 134,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 143,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 147,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 156,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 161,
     .y = 5,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_GOOMBO}},
    {.x = 163,
     .y = 5,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_GOOMBO}},
    {.x = 174,
     .y = 2,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_GOOMBO}},
    {.x = 176,
     .y = 2,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_GOOMBO}},
    {.x = 178,
     .y = 2,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_GOOMBO}},
    {.x = 185,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 189,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 193,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 198,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_HONEN}},
    {.x = 209,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_GOOMBO}},
    {.x = 214,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_GOOMBO}},
    {.x = 222,
     .y = 11,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_GOOMBO}},
    {.x = 254,
     .y = 2,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_GOOMBO}},
    {.x = 271,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_GOOMBO}},
    {.x = 280,
     .y = 15,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_GOOMBO}},
    {.x = 288,
     .y = 5,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.platform_direction = DIRECTION_VERTICAL}},
    {.x = 304,
     .y = 5,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.platform_direction = DIRECTION_VERTICAL}},
    {.x = 313,
     .y = 3,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_GOOMBO}},   // WIP: falling platform
    {.x = 314,
     .y = 3,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_GOOMBO}}};   // WIP: falling platform

const size_t level_2_1_lookup_size =
    sizeof(level_2_1_lookup) / sizeof(level_2_1_lookup[0]);