#pragma bank 255

#include "lookup_table_4_1.h"

BANKREF(level_4_1_lookup_bank)

const level_object level_4_1_lookup[] = {
    {.x = 31,
 .y = 11,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 35,
 .y = 14,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 50,
 .y = 14,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 55,
 .y = 13,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PIONPI}},
    {.x = 63,
 .y = 5,
 .type = OBJECT_TYPE_PLATFORM_MOVING,
 .data.platform_moving = {.range = 6,
 .platform_direction = DIRECTION_VERTICAL}},
    {.x = 69,
 .y = 4,
 .type = OBJECT_TYPE_PLATFORM_MOVING,
 .data.platform_moving = {.range = 6,
 .platform_direction = DIRECTION_VERTICAL}},
    {.x = 90,
 .y = 14,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 95,
 .y = 13,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PIONPI}},
    {.x = 113,
 .y = 12,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 118,
 .y = 12,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PIONPI}},
    {.x = 129,
 .y = 12,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PIONPI}},
    {.x = 130,
 .y = 12,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 134,
 .y = 12,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 147,
 .y = 13,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PIONPI}},
    {.x = 150,
 .y = 14,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 154,
 .y = 9,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PIONPI}},
    {.x = 166,
 .y = 14,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 168,
 .y = 12,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 171,
 .y = 10,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 182,
 .y = 11,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 188,
 .y = 8,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PIONPI}},
    {.x = 189,
 .y = 8,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 196,
 .y = 10,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 200,
 .y = 7,
 .type = OBJECT_TYPE_PLATFORM_MOVING,
 .data.platform_moving = {.range = 6,
 .platform_direction = DIRECTION_VERTICAL}},
    {.x = 209,
 .y = 12,
 .type = OBJECT_TYPE_PLATFORM_MOVING,
 .data.platform_moving = {.range = 6,
 .platform_direction = DIRECTION_VERTICAL}},
    {.x = 223,
 .y = 12,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 227,
 .y = 11,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 231,
 .y = 11,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 235,
 .y = 14,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 243,
 .y = 12,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 247,
 .y = 11,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 250,
 .y = 13,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_GOOMBO}},
    {.x = 299,
 .y = 3,
 .type = OBJECT_TYPE_PLATFORM_FALLING,
},
    {.x = 300,
 .y = 3,
 .type = OBJECT_TYPE_PLATFORM_FALLING,
},
    {.x = 304,
 .y = 3,
 .type = OBJECT_TYPE_PLATFORM_FALLING,
},
    {.x = 305,
 .y = 3,
 .type = OBJECT_TYPE_PLATFORM_FALLING,
},
    {.x = 308,
 .y = 4,
 .type = OBJECT_TYPE_PLATFORM_FALLING,
},
    {.x = 309,
 .y = 4,
 .type = OBJECT_TYPE_PLATFORM_FALLING,
},
    {.x = 314,
 .y = 5,
 .type = OBJECT_TYPE_PLATFORM_MOVING,
 .data.platform_moving = {.range = 6,
 .platform_direction = DIRECTION_VERTICAL}},
    {.x = 324,
 .y = 14,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 336,
 .y = 8,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PIONPI}},
    {.x = 346,
 .y = 13,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PIONPI}},
    {.x = 354,
 .y = 12,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 356,
 .y = 12,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PIONPI}},
    {.x = 358,
 .y = 12,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 360,
 .y = 6,
 .type = OBJECT_TYPE_PLATFORM_MOVING,
 .data.platform_moving = {.range = 6,
 .platform_direction = DIRECTION_VERTICAL}},
    {.x = 389,
 .y = 14,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 393,
 .y = 12,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 396,
 .y = 8,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 397,
 .y = 6,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 415,
 .y = 11,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PIONPI}},
    {.x = 415,
 .y = 6,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PIONPI}},
    {.x = 415,
 .y = 3,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_PIONPI}},
    {.x = 431,
 .y = 14,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 433,
 .y = 12,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 435,
 .y = 9,
 .type = OBJECT_TYPE_ENEMY,
 .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 440,
 .y = 1,
 .type = OBJECT_TYPE_PLATFORM_MOVING,
 .data.platform_moving = {.range = 6,
 .platform_direction = DIRECTION_VERTICAL}}
};

const size_t level_4_1_lookup_size =
    sizeof(level_4_1_lookup) / sizeof(level_4_1_lookup[0]);