#pragma bank 255

#include "lookup_table_3_1.h"

BANKREF(level_3_1_lookup_bank)

const level_object level_3_1_lookup[] = {
    {.x = 30,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BATADON}},
    {.x = 40,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {
        .x = 48,
        .y = 13,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 49,
        .y = 13,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 50,
        .y = 13,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 51,
        .y = 13,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 52,
        .y = 13,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 53,
        .y = 13,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {.x = 59,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 72,
     .y = 12,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 96,
     .y = 1,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BATADON}},
    {.x = 99,
     .y = 2,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 105,
     .y = 4,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 109,
     .y = 10,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 117,
     .y = 12,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 120,
     .y = 12,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 125,
     .y = 9,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 142,
     .y = 11,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 152,
     .y = 12,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 162,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 175,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_TOKOTOKO}},
    {.x = 178,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 190,
     .y = 8,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_TOKOTOKO}},
    {.x = 198,
     .y = 2,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BATADON}},
    {.x = 213,
     .y = 6,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 218,
     .y = 2,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BATADON}},
    {.x = 220,
     .y = 14,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 229,
     .y = 4,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 231,
     .y = 3,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 242,
     .y = 11,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 252,
     .y = 12,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 268,
     .y = 7,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 270,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_TOKOTOKO}},
    {.x = 272,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_TOKOTOKO}},
    {.x = 274,
     .y = 3,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BATADON}},
    {.x = 274,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_TOKOTOKO}},
    {.x = 285,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BATADON}},
    {.x = 288,
     .y = 7,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 298,
     .y = 9,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_TOKOTOKO}},
    {.x = 357,
     .y = 11,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 444,
     .y = 7,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {
        .x = 453,
        .y = 5,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 456,
        .y = 3,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    }};

const size_t level_3_1_lookup_size =
    sizeof(level_3_1_lookup) / sizeof(level_3_1_lookup[0]);