//AUTOGENERATED FILE FROM png2asset
// Conversion args: /3_1_10.png -o /level_3_1_10.c -source_tileset /common.png -source_tileset /easton.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_level_3_1_10_H
#define METASPRITE_level_3_1_10_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_3_1_10_TILE_ORIGIN 40
#define level_3_1_10_TILE_W 8
#define level_3_1_10_TILE_H 8
#define level_3_1_10_WIDTH 160
#define level_3_1_10_HEIGHT 128
#define level_3_1_10_TILE_COUNT 0
#define level_3_1_10_PALETTE_COUNT 1
#define level_3_1_10_COLORS_PER_PALETTE 4
#define level_3_1_10_TOTAL_COLORS 4
#define level_3_1_10_MAP_ATTRIBUTES 0
extern const unsigned char level_3_1_10_map[320];
#define level_3_1_10_map_attributes level_3_1_10_map

BANKREF_EXTERN(level_3_1_10)


#endif
