//AUTOGENERATED FILE FROM png2asset
// Conversion args: /1_1_06.png -o /level_1_1_06.c -source_tileset /common.png -source_tileset /birabuto.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_level_1_1_06_H
#define METASPRITE_level_1_1_06_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_1_1_06_TILE_ORIGIN 40
#define level_1_1_06_TILE_W 8
#define level_1_1_06_TILE_H 8
#define level_1_1_06_WIDTH 160
#define level_1_1_06_HEIGHT 128
#define level_1_1_06_TILE_COUNT 0
#define level_1_1_06_PALETTE_COUNT 1
#define level_1_1_06_COLORS_PER_PALETTE 4
#define level_1_1_06_TOTAL_COLORS 4
#define level_1_1_06_MAP_ATTRIBUTES 0
extern const unsigned char level_1_1_06_map[320];
#define level_1_1_06_map_attributes level_1_1_06_map

BANKREF_EXTERN(level_1_1_06)


#endif
