//AUTOGENERATED FILE FROM png2asset
// Conversion args: /2_3_05.png -o /level_2_3_05.c -source_tileset /common.png -source_tileset /muda.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_level_2_3_05_H
#define METASPRITE_level_2_3_05_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_2_3_05_TILE_ORIGIN 40
#define level_2_3_05_TILE_W 8
#define level_2_3_05_TILE_H 8
#define level_2_3_05_WIDTH 160
#define level_2_3_05_HEIGHT 128
#define level_2_3_05_TILE_COUNT 0
#define level_2_3_05_PALETTE_COUNT 1
#define level_2_3_05_COLORS_PER_PALETTE 4
#define level_2_3_05_TOTAL_COLORS 4
#define level_2_3_05_MAP_ATTRIBUTES 0
extern const unsigned char level_2_3_05_map[320];
#define level_2_3_05_map_attributes level_2_3_05_map

BANKREF_EXTERN(level_2_3_05)


#endif
