//AUTOGENERATED FILE FROM png2asset
// Conversion args: /stage_end.png -o /stage_end.c -source_tileset /common.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_stage_end_H
#define METASPRITE_stage_end_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define stage_end_TILE_ORIGIN 40
#define stage_end_TILE_W 8
#define stage_end_TILE_H 8
#define stage_end_WIDTH 160
#define stage_end_HEIGHT 128
#define stage_end_TILE_COUNT 0
#define stage_end_PALETTE_COUNT 1
#define stage_end_COLORS_PER_PALETTE 4
#define stage_end_TOTAL_COLORS 4
#define stage_end_MAP_ATTRIBUTES 0
extern const unsigned char stage_end_map[320];
#define stage_end_map_attributes stage_end_map

BANKREF_EXTERN(stage_end)


#endif
