//AUTOGENERATED FILE FROM png2asset
// Conversion args: /underground_7.png -o /underground_7.c -source_tileset /common.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_underground_7_H
#define METASPRITE_underground_7_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define underground_7_TILE_ORIGIN 40
#define underground_7_TILE_W 8
#define underground_7_TILE_H 8
#define underground_7_WIDTH 160
#define underground_7_HEIGHT 128
#define underground_7_TILE_COUNT 0
#define underground_7_PALETTE_COUNT 1
#define underground_7_COLORS_PER_PALETTE 4
#define underground_7_TOTAL_COLORS 4
#define underground_7_MAP_ATTRIBUTES 0
extern const unsigned char underground_7_map[320];
#define underground_7_map_attributes underground_7_map

BANKREF_EXTERN(underground_7)


#endif
