//AUTOGENERATED FILE FROM png2asset
// Conversion args: /underground_1.png -o /underground_1.c -source_tileset /common.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_underground_1_H
#define METASPRITE_underground_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define underground_1_TILE_ORIGIN 40
#define underground_1_TILE_W 8
#define underground_1_TILE_H 8
#define underground_1_WIDTH 160
#define underground_1_HEIGHT 128
#define underground_1_TILE_COUNT 0
#define underground_1_PALETTE_COUNT 1
#define underground_1_COLORS_PER_PALETTE 4
#define underground_1_TOTAL_COLORS 4
#define underground_1_MAP_ATTRIBUTES 0
extern const unsigned char underground_1_map[320];
#define underground_1_map_attributes underground_1_map

BANKREF_EXTERN(underground_1)


#endif
