//AUTOGENERATED FILE FROM png2asset
// Conversion args: /underground_4.png -o /underground_4.c -source_tileset /common.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_underground_4_H
#define METASPRITE_underground_4_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define underground_4_TILE_ORIGIN 40
#define underground_4_TILE_W 8
#define underground_4_TILE_H 8
#define underground_4_WIDTH 160
#define underground_4_HEIGHT 128
#define underground_4_TILE_COUNT 0
#define underground_4_PALETTE_COUNT 1
#define underground_4_COLORS_PER_PALETTE 4
#define underground_4_TOTAL_COLORS 4
#define underground_4_MAP_ATTRIBUTES 0
extern const unsigned char underground_4_map[320];
#define underground_4_map_attributes underground_4_map

BANKREF_EXTERN(underground_4)


#endif
