//AUTOGENERATED FILE FROM png2asset
// Conversion args: /underground_2.png -o /underground_2.c -source_tileset /common.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_underground_2_H
#define METASPRITE_underground_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define underground_2_TILE_ORIGIN 40
#define underground_2_TILE_W 8
#define underground_2_TILE_H 8
#define underground_2_WIDTH 160
#define underground_2_HEIGHT 128
#define underground_2_TILE_COUNT 0
#define underground_2_PALETTE_COUNT 1
#define underground_2_COLORS_PER_PALETTE 4
#define underground_2_TOTAL_COLORS 4
#define underground_2_MAP_ATTRIBUTES 0
extern const unsigned char underground_2_map[320];
#define underground_2_map_attributes underground_2_map

BANKREF_EXTERN(underground_2)


#endif
