//AUTOGENERATED FILE FROM png2asset
// Conversion args: /underground_3.png -o /underground_3.c -source_tileset /common.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_underground_3_H
#define METASPRITE_underground_3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define underground_3_TILE_ORIGIN 40
#define underground_3_TILE_W 8
#define underground_3_TILE_H 8
#define underground_3_WIDTH 160
#define underground_3_HEIGHT 128
#define underground_3_TILE_COUNT 0
#define underground_3_PALETTE_COUNT 1
#define underground_3_COLORS_PER_PALETTE 4
#define underground_3_TOTAL_COLORS 4
#define underground_3_MAP_ATTRIBUTES 0
extern const unsigned char underground_3_map[320];
#define underground_3_map_attributes underground_3_map

BANKREF_EXTERN(underground_3)


#endif
