//AUTOGENERATED FILE FROM png2asset
// Conversion args: /underground_8.png -o /underground_8.c -source_tileset /common.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_underground_8_H
#define METASPRITE_underground_8_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define underground_8_TILE_ORIGIN 40
#define underground_8_TILE_W 8
#define underground_8_TILE_H 8
#define underground_8_WIDTH 160
#define underground_8_HEIGHT 128
#define underground_8_TILE_COUNT 0
#define underground_8_PALETTE_COUNT 1
#define underground_8_COLORS_PER_PALETTE 4
#define underground_8_TOTAL_COLORS 4
#define underground_8_MAP_ATTRIBUTES 0
extern const unsigned char underground_8_map[320];
#define underground_8_map_attributes underground_8_map

BANKREF_EXTERN(underground_8)


#endif
