//AUTOGENERATED FILE FROM png2asset
// Conversion args: /underground_0.png -o /underground_0.c -source_tileset /common.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_underground_0_H
#define METASPRITE_underground_0_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define underground_0_TILE_ORIGIN 40
#define underground_0_TILE_W 8
#define underground_0_TILE_H 8
#define underground_0_WIDTH 160
#define underground_0_HEIGHT 128
#define underground_0_TILE_COUNT 0
#define underground_0_PALETTE_COUNT 1
#define underground_0_COLORS_PER_PALETTE 4
#define underground_0_TOTAL_COLORS 4
#define underground_0_MAP_ATTRIBUTES 0
extern const unsigned char underground_0_map[320];
#define underground_0_map_attributes underground_0_map

BANKREF_EXTERN(underground_0)


#endif
