//AUTOGENERATED FILE FROM png2asset
// Conversion args: /underground_9.png -o /underground_9.c -source_tileset /common.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_underground_9_H
#define METASPRITE_underground_9_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define underground_9_TILE_ORIGIN 40
#define underground_9_TILE_W 8
#define underground_9_TILE_H 8
#define underground_9_WIDTH 160
#define underground_9_HEIGHT 128
#define underground_9_TILE_COUNT 0
#define underground_9_PALETTE_COUNT 1
#define underground_9_COLORS_PER_PALETTE 4
#define underground_9_TOTAL_COLORS 4
#define underground_9_MAP_ATTRIBUTES 0
extern const unsigned char underground_9_map[320];
#define underground_9_map_attributes underground_9_map

BANKREF_EXTERN(underground_9)


#endif
