//AUTOGENERATED FILE FROM png2asset
// Conversion args: /underground_6.png -o /underground_6.c -source_tileset /common.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_underground_6_H
#define METASPRITE_underground_6_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define underground_6_TILE_ORIGIN 40
#define underground_6_TILE_W 8
#define underground_6_TILE_H 8
#define underground_6_WIDTH 160
#define underground_6_HEIGHT 128
#define underground_6_TILE_COUNT 0
#define underground_6_PALETTE_COUNT 1
#define underground_6_COLORS_PER_PALETTE 4
#define underground_6_TOTAL_COLORS 4
#define underground_6_MAP_ATTRIBUTES 0
extern const unsigned char underground_6_map[320];
#define underground_6_map_attributes underground_6_map

BANKREF_EXTERN(underground_6)


#endif
