//AUTOGENERATED FILE FROM png2asset
// Conversion args: /underground_5.png -o /underground_5.c -source_tileset /common.png -map -noflip -keep_duplicate_tiles -tile_origin 40 -b 255

#ifndef METASPRITE_underground_5_H
#define METASPRITE_underground_5_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define underground_5_TILE_ORIGIN 40
#define underground_5_TILE_W 8
#define underground_5_TILE_H 8
#define underground_5_WIDTH 160
#define underground_5_HEIGHT 128
#define underground_5_TILE_COUNT 0
#define underground_5_PALETTE_COUNT 1
#define underground_5_COLORS_PER_PALETTE 4
#define underground_5_TOTAL_COLORS 4
#define underground_5_MAP_ATTRIBUTES 0
extern const unsigned char underground_5_map[320];
#define underground_5_map_attributes underground_5_map

BANKREF_EXTERN(underground_5)


#endif
