#pragma bank 255

//AUTOGENERATED FILE FROM png2asset
// Conversion args: /birabuto_torch.png -o /birabuto_torch.c -map -tiles_only -noflip -keep_duplicate_tiles -b 255 -tile_origin 96

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(birabuto_torch)

const palette_color_t birabuto_torch_palettes[4] = {
	RGB8(255,255,255), RGB8( 85, 85, 85), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	};

const uint8_t birabuto_torch_tiles[16] = {
	0x00,0x00,0x00,0x00,0x00,0x00,0x10,0x00,0x38,0x00,0x38,0x00,0x28,0x00,0x10,0x00
	};

