//AUTOGENERATED FILE FROM png2asset
// Conversion args: /birabuto_torch.png -o /birabuto_torch.c -map -tiles_only -noflip -keep_duplicate_tiles -b 255 -tile_origin 96

#ifndef METASPRITE_birabuto_torch_H
#define METASPRITE_birabuto_torch_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define birabuto_torch_TILE_ORIGIN 96
#define birabuto_torch_TILE_W 8
#define birabuto_torch_TILE_H 8
#define birabuto_torch_WIDTH 8
#define birabuto_torch_HEIGHT 8
#define birabuto_torch_TILE_COUNT 1
#define birabuto_torch_PALETTE_COUNT 1
#define birabuto_torch_COLORS_PER_PALETTE 4
#define birabuto_torch_TOTAL_COLORS 4

BANKREF_EXTERN(birabuto_torch)

extern const palette_color_t birabuto_torch_palettes[4];
extern const uint8_t birabuto_torch_tiles[16];

#endif
