//AUTOGENERATED FILE FROM png2asset
// Conversion args: /chai.png -o /chai.c -map -tiles_only -noflip -keep_duplicate_tiles -b 255 -tile_origin 96

#ifndef METASPRITE_chai_H
#define METASPRITE_chai_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define chai_TILE_ORIGIN 96
#define chai_TILE_W 8
#define chai_TILE_H 8
#define chai_WIDTH 80
#define chai_HEIGHT 72
#define chai_TILE_COUNT 90
#define chai_PALETTE_COUNT 1
#define chai_COLORS_PER_PALETTE 4
#define chai_TOTAL_COLORS 4

BANKREF_EXTERN(chai)

extern const palette_color_t chai_palettes[4];
extern const uint8_t chai_tiles[1440];

#endif
