//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_easton_H
#define METASPRITE_easton_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define easton_TILE_ORIGIN 96
#define easton_TILE_W 8
#define easton_TILE_H 8
#define easton_WIDTH 80
#define easton_HEIGHT 56
#define easton_TILE_COUNT 70
#define easton_PALETTE_COUNT 1
#define easton_COLORS_PER_PALETTE 4
#define easton_TOTAL_COLORS 4

BANKREF_EXTERN(easton)

extern const palette_color_t easton_palettes[4];
extern const uint8_t easton_tiles[1120];

#endif
