//AUTOGENERATED FILE FROM png2asset
// Conversion args: /enemies_large_muda.png -o /enemies_large_muda.c -sw 16 -sh 16 -spr8x8 -keep_palette_order -tile_origin 43 -b 255

#ifndef METASPRITE_enemies_large_muda_H
#define METASPRITE_enemies_large_muda_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define enemies_large_muda_TILE_ORIGIN 43
#define enemies_large_muda_TILE_W 8
#define enemies_large_muda_TILE_H 8
#define enemies_large_muda_WIDTH 16
#define enemies_large_muda_HEIGHT 16
#define enemies_large_muda_TILE_COUNT 22
#define enemies_large_muda_PALETTE_COUNT 1
#define enemies_large_muda_COLORS_PER_PALETTE 4
#define enemies_large_muda_TOTAL_COLORS 4
#define enemies_large_muda_PIVOT_X 8
#define enemies_large_muda_PIVOT_Y 8
#define enemies_large_muda_PIVOT_W 16
#define enemies_large_muda_PIVOT_H 16
extern const metasprite_t* const enemies_large_muda_metasprites[8];

BANKREF_EXTERN(enemies_large_muda)

extern const palette_color_t enemies_large_muda_palettes[4];
extern const uint8_t enemies_large_muda_tiles[352];

#endif
