//AUTOGENERATED FILE FROM png2asset
// Conversion args: /enemies_large_birabuto.png -o /enemies_large_birabuto.c -sw 16 -sh 16 -spr8x8 -keep_palette_order -tile_origin 43 -b 255

#ifndef METASPRITE_enemies_large_birabuto_H
#define METASPRITE_enemies_large_birabuto_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define enemies_large_birabuto_TILE_ORIGIN 43
#define enemies_large_birabuto_TILE_W 8
#define enemies_large_birabuto_TILE_H 8
#define enemies_large_birabuto_WIDTH 16
#define enemies_large_birabuto_HEIGHT 16
#define enemies_large_birabuto_TILE_COUNT 28
#define enemies_large_birabuto_PALETTE_COUNT 1
#define enemies_large_birabuto_COLORS_PER_PALETTE 4
#define enemies_large_birabuto_TOTAL_COLORS 4
#define enemies_large_birabuto_PIVOT_X 8
#define enemies_large_birabuto_PIVOT_Y 8
#define enemies_large_birabuto_PIVOT_W 16
#define enemies_large_birabuto_PIVOT_H 16
extern const metasprite_t* const enemies_large_birabuto_metasprites[9];

BANKREF_EXTERN(enemies_large_birabuto)

extern const palette_color_t enemies_large_birabuto_palettes[4];
extern const uint8_t enemies_large_birabuto_tiles[448];

#endif
