//AUTOGENERATED FILE FROM png2asset
// Conversion args: /title.png -o /title.c -map -noflip -b 255 -tile_origin 96

#ifndef METASPRITE_title_H
#define METASPRITE_title_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define title_TILE_ORIGIN 96
#define title_TILE_W 8
#define title_TILE_H 8
#define title_WIDTH 160
#define title_HEIGHT 144
#define title_TILE_COUNT 101
#define title_PALETTE_COUNT 2
#define title_COLORS_PER_PALETTE 4
#define title_TOTAL_COLORS 8
#define title_MAP_ATTRIBUTES 0
extern const unsigned char title_map[360];
#define title_map_attributes title_map

BANKREF_EXTERN(title)

extern const palette_color_t title_palettes[8];
extern const uint8_t title_tiles[1616];

#endif
