//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_title_H
#define METASPRITE_title_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define title_TILE_ORIGIN 96
#define title_TILE_W 8
#define title_TILE_H 8
#define title_WIDTH 160
#define title_HEIGHT 144
#define title_TILE_COUNT 360
#define title_PALETTE_COUNT 2
#define title_COLORS_PER_PALETTE 4
#define title_TOTAL_COLORS 8

BANKREF_EXTERN(title)

extern const palette_color_t title_palettes[8];
extern const uint8_t title_tiles[5760];

#endif
