#ifndef GLOBAL_H
#define GLOBAL_H

#define TILE_SIZE 8
#define DEVICE_SCREEN_HEIGHT 18
#define DEVICE_SCREEN_WIDTH 20
#define WINDOW_HEIGHT_TILE 2
#define WINDOW_WIDTH_TILE DEVICE_SCREEN_WIDTH
#define WINDOW_SIZE WINDOW_WIDTH_TILE * WINDOW_HEIGHT_TILE
#define WINDOW_X MINWNDPOSX
#define WINDOW_Y MINWNDPOSY

#define INITIAL_LIVES 3
#define TIME_SHIFT 5
#define TIME_INITIAL_VALUE 400 << TIME_SHIFT
#define GRAVITY 42
#define JUMP_SPEED 32
#define MAX_JUMP 512
#define PLAYER_SPEED_WALK 16
#define PLAYER_SPEED_RUN 20
#define PLAYER_DRAW_OFFSET_X 4
#define PLAYER_DRAW_OFFSET_Y mario_HEIGHT / 2

#define LOOP_PER_ANIMATION_FRAME 5
#define MARIO_HALF_WIDTH 4
#define MARIO_SPRITE_COUNT 4

#define DEVICE_SCREEN_PX_WIDTH_HALF DEVICE_SCREEN_PX_WIDTH / 2
#define MARGIN_TOP 2
#define MARGIN_TOP_PX 2 * TILE_SIZE
#define DEVICE_SPRITE_OFFSET_Y 2

#endif
