#pragma bank 255

#include "lookup_table_3_2.h"

BANKREF(level_3_2_lookup)

const level_object level_3_2_lookup[] = {
    {.x = 7,
     .y = 3,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_SUU}},
    {.x = 11,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 38,
     .y = 3,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_SUU}},
    {.x = 45,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 51,
     .y = 5,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_SUU}},
    {.x = 53,
     .y = 5,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_SUU}},
    {.x = 58,
     .y = 11,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 60,
     .y = 2,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_SUU}},
    {.x = 67,
     .y = 1,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 80,
     .y = 4,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_SUU}},
    {.x = 81,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KUMO}},
    {.x = 92,
     .y = 3,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_SUU}},
    {.x = 103,
     .y = 0,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 112,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 125,
     .y = 10,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 136,
     .y = 3,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_SUU}},
    {.x = 138,
     .y = 9,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KUMO}},
    {.x = 140,
     .y = 5,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_SUU}},
    {.x = 147,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 159,
     .y = 6,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KUMO}},
    {.x = 163,
     .y = 11,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 166,
     .y = 2,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_SUU}},
    {.x = 173,
     .y = 10,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 198,
     .y = 9,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KUMO}},
    {.x = 247,
     .y = 12,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_BULLET}},
    {.x = 249,
     .y = 5,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_SUU}},
    {.x = 252,
     .y = 13,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KUMO}},
    {.x = 258,
     .y = 11,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_PLANT}},
    {.x = 264,
     .y = 6,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {.x = 272,
     .y = 11,
     .type = OBJECT_TYPE_ENEMY,
     .data.enemy = {.type = ENEMY_KOOPA}},
    {.x = 275,
     .y = 5,
     .type = OBJECT_TYPE_PLATFORM_MOVING,
     .data.platform_moving = {.range = 6,
                              .platform_direction = DIRECTION_VERTICAL}},
    {
        .x = 281,
        .y = 8,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 282,
        .y = 8,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 285,
        .y = 7,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 286,
        .y = 7,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 293,
        .y = 8,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 296,
        .y = 9,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 297,
        .y = 9,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 301,
        .y = 9,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 304,
        .y = 8,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 307,
        .y = 7,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 310,
        .y = 6,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 313,
        .y = 5,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    },
    {
        .x = 316,
        .y = 3,
        .type = OBJECT_TYPE_PLATFORM_FALLING,
    }};
