#ifndef TILESET_INDEX_H
#define TILESET_INDEX_H

enum tileset_index_common {
  TILE_EMPTY = 0x28,
  TILE_INTEROGATION_BLOCK = 0x2C,
  TILE_EMPTIED = 0x29,
  BREAKABLE_BLOCK = 0x2A,
  TILE_UNBREAKABLE = 0x2B,
  TILE_COIN = 0x37,
  PIPE_TOP_LEFT = 0x30,
  PIPE_TOP_RIGHT = 0x31,
  PIPE_CENTER_LEFT = 0x3E,
  PIPE_CENTER_RIGHT = 0x3F,
  SWITCH = 0x3D,
  METAL_GATE = 0x3C,
  PIPE_HORIZONTAL_1 = 0x4A,
  PIPE_HORIZONTAL_2 = 0x4B,
  PIPE_HORIZONTAL_3 = 0x4C,
  PIPE_HORIZONTAL_4 = 0x4D,
  PIPE_HORIZONTAL_5 = 0x58,
  PIPE_HORIZONTAL_6 = 0x59,
  PIPE_HORIZONTAL_7 = 0x5A,
  PIPE_HORIZONTAL_8 = 0x5B,
  METAL_BLOCK_LEFT = 0x56,
  METAL_BLOCK_RIGHT = 0x57
};

enum tileset_index_birabuto {
  GREY_BLOCK = 0x61,
  TILE_TORCH = 0x72,
  TILE_FLOOR = 0x75,
  TILE_FLOOR_BIS = 0x7F,
  OBLIC_LINE_LEFT = 0x68,
  OBLIC_LINE_RIGHT = 0x69,
  STONE_LEFT = 0x5C,
  STONE_RIGHT = 0x5D,
  TILED_FLOOR = 0x91,
  STONE_BIS_LEFT = 0x99,
  STONE_BIS_RIGHT = 0x9A,
  BRICK_BLOCK = 0x9B,
  PALM_TREE_LEFT = 0x79,
  PALM_TREE_CENTER = 0x7A,
  PALM_TREE_RIGHT = 0x7B
};

enum tileset_index_muda {
  MUDA_PLATEFORM_LEFT = 0x83,
  MUDA_PLATEFORM_CENTER = 0x84,
  MUDA_PLATEFORM_RIGHT = 0x85,
  BIG_BLOCK_TOP_LEFT = 0x86,
  BIG_BLOCK_TOP_RIGHT = 0X87,
  BIG_BLOCK_BOTTOM_LEFT = 0X90,
  BIG_BLOCK_BOTTOM_RIGHT = 0X91,
  OCEAN_FLOOR_LEFT = 0x88,
  OCEAN_FLOOR_RIGHT = 0x89,
  MUDA_BRIDGE = 0x99,
  HALF_BIG_BLOCK_TOP_LEFT = 0x9A,
  HALF_BIG_BLOCK_TOP_RIGHT = 0X9B
};

enum tileset_index_easton {
  EASTON_FLOOR_1 = 0x9D,
  EASTON_FLOOR_2 = 0x9C,
  EASTON_STONE_PLATEFORM_1 = 0x87,
  EASTON_STONE_PLATEFORM_2 = 0x91,
  EASTON_STONE_PLATEFORM_3 = 0x9E,
  EASTON_STONE_PLATEFORM_4 = 0x9F,
  EASTON_STONE_PLATEFORM_BOTTOM = 0x9B,
  EASTON_LARGE_BLACK_BLOCK_TOP_LEFT = 0X72,
  EASTON_LARGE_BLACK_BLOCK_TOP_RIGHT = 0X73,
  EASTON_LARGE_BLACK_BLOCK_BOTOM_LEFT = 0X7C,
  EASTON_LARGE_BLACK_BLOCK_BOTTOM_RIGHT = 0X7D,
  EASTON_BLOCK = 0xA0,
  EASTON_STONE_PLATEFORM_LEFT = 0xA1,
  EASTON_STONE_PLATEFORM_RIGHT = 0xA2
};

enum tileset_index_chai {
  CHAI_FLOOR_LEFT = 0x88,
  CHAI_FLOOR_MIDDLE_1 = 0x89,
  CHAI_FLOOR_MIDDLE_2 = 0x8A,
  CHAI_FLOOR_MIDDLE_RIGHT = 0x8B,
  CHAI_GREY_BLOCK = 0x93,
  CHAI_PIPE = 0xAF,
  CHAI_PIPE_LEFT = 0xB6,
  CHAI_PIPE_RIGHT = 0xB7,
  CHAI_PIPE_BOTTOM_LEFT = 0xB8,
  CHAI_PIPE_BOTTOM_RIGHT = 0xB9,
  CHAI_BLOCK = 0x63,
  CHAI_BRICK_BLOCK = 0x83,
  CHAI_BLACK_BLOCK_LEFT = 0x96,
  CHAI_BLACK_BLOCK_RIGHT = 0x97,
  CHAI_FIRE_BLOCK = 0x9C
};

#endif